name: main
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10, 11, 12, 13, 14 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Run static type checking
        run: yarn type-check
      - name: Run unit tests
        run: yarn coverage
